# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todolist.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 543)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(31)
        font.setItalic(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(185, 219, 235);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.screen = QtWidgets.QScrollArea(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(50, 240, 181, 221))
        self.screen.setStyleSheet("background-color: rgb(178, 213, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.screen.setWidgetResizable(True)
        self.screen.setObjectName("screen")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 179, 219))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.screen.setWidget(self.scrollAreaWidgetContents)
        self.Input = QtWidgets.QLineEdit(self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(50, 180, 181, 31))
        self.Input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Input.setObjectName("Input")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(320, 130, 181, 31))
        self.add.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.add.setObjectName("add")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(29)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(320, 180, 181, 31))
        self.search.setStyleSheet("background-color: rgb(255, 155, 179);\n"
"background-color: rgb(255, 190, 111);")
        self.search.setObjectName("search")
        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(320, 230, 181, 31))
        self.delete_2.setStyleSheet("background-color: rgb(255, 155, 179);\n"
"background-color: rgb(249, 240, 107);")
        self.delete_2.setObjectName("delete_2")
        self.DA = QtWidgets.QPushButton(self.centralwidget)
        self.DA.setGeometry(QtCore.QRect(320, 280, 181, 31))
        self.DA.setStyleSheet("background-color: rgb(255, 155, 179);\n"
"background-color: rgb(143, 240, 164);")
        self.DA.setObjectName("DA")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(320, 430, 181, 31))
        self.exit.setStyleSheet("background-color: rgb(255, 155, 179);")
        self.exit.setObjectName("exit")
        self.SN = QtWidgets.QPushButton(self.centralwidget)
        self.SN.setGeometry(QtCore.QRect(320, 330, 181, 31))
        self.SN.setStyleSheet("background-color: rgb(98, 160, 234);")
        self.SN.setObjectName("SN")
        self.SD = QtWidgets.QPushButton(self.centralwidget)
        self.SD.setGeometry(QtCore.QRect(320, 380, 181, 31))
        self.SD.setStyleSheet("background-color: rgb(255, 155, 179);\n"
"background-color: rgb(220, 138, 221);")
        self.SD.setObjectName("SD")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 181, 21))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add.setText(_translate("MainWindow", "Add Le Task"))
        self.label.setText(_translate("MainWindow", "Le To Do-List"))
        self.search.setText(_translate("MainWindow", "Search for Le task"))
        self.delete_2.setText(_translate("MainWindow", "Delete Le Task"))
        self.DA.setText(_translate("MainWindow", "Delete All Tasks"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.SN.setText(_translate("MainWindow", "Sorts Tasks by name"))
        self.SD.setText(_translate("MainWindow", "Sort Le Task by Deadline"))
        self.label_2.setText(_translate("MainWindow", "Hi  (>u<) /"))
